@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v2
@api_key = {{$dotenv API_KEY}}

### Bienvenida
GET {{root}}

### GET Distritos
GET {{baseUrl}}/distritos
X-Api-Key: {{api_key}}

### GET 6 Distrito Saltillo
GET {{baseUrl}}/distritos/6
X-Api-Key: {{api_key}}

### GET Oficinas del Distrito 6
GET {{baseUrl}}/oficinas
    ?distrito_id=6
X-Api-Key: {{api_key}}

### Oficina 69 J PRIMERO FAMILIAR SALTILLO
GET {{baseUrl}}/oficinas/69
X-Api-Key: {{api_key}}

### GET Servicios de la Oficina
GET {{baseUrl}}/cit_oficinas_servicios
    ?oficina_id=69
X-Api-Key: {{api_key}}

### GET Dias para elegir
GET {{baseUrl}}/cit_dias_disponibles
    ?oficina_id=69
X-Api-Key: {{api_key}}

### GET Horas para elegir
GET {{baseUrl}}/cit_horas_disponibles
    ?oficina_id=69
    &cit_servicio_id=2
    &fecha=2022-10-20
X-Api-Key: {{api_key}}

### GET Cliente por ID
GET {{baseUrl}}/cit_clientes/4653
X-Api-Key: {{api_key}}

### GET Cliente por ID
GET {{baseUrl}}/cit_clientes/perfil
    ?cit_cliente_id=4653
X-Api-Key: {{api_key}}

### GET Cliente por email
GET {{baseUrl}}/cit_clientes/perfil
    ?cit_cliente_email=anonymous@company.com
X-Api-Key: {{api_key}}

### GET Cliente por CURP
GET {{baseUrl}}/cit_clientes/perfil
    ?cit_cliente_curp=XXXX00000000000XXX
X-Api-Key: {{api_key}}

### POST crear cita
POST {{baseUrl}}/cit_citas/nueva
X-Api-Key: {{api_key}}

{
    "cit_cliente_id": 12070,
    "oficina_id": 71,
    "cit_servicio_id": 2,
    "fecha": "2022-10-25",
    "hora_minuto": "10:30",
    "notas": "Cita de prueba"
}

### GET cita
GET {{baseUrl}}/cit_citas/30892
X-Api-Key: {{api_key}}

### GET mis citas por ID de cliente
GET {{baseUrl}}/cit_citas/mis_citas
    ?cit_cliente_id=12070
X-Api-Key: {{api_key}}

### GET mis citas por CURP de cliente
GET {{baseUrl}}/cit_citas/mis_citas
    ?cit_cliente_curp=XXXXXX00000000000
X-Api-Key: {{api_key}}

### GET mis citas por email de cliente
GET {{baseUrl}}/cit_citas/mis_citas
    ?cit_cliente_email=anonymous@company.com
X-Api-Key: {{api_key}}

### POST cancelar una cita PENDIENTE
POST {{baseUrl}}/cit_citas/cancelar
X-Api-Key: {{api_key}}

{
    "id": 32238,
    "cit_cliente_id": 999
}
