@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v2
@api_key = {{$dotenv API_KEY}}

### Bienvenida
GET {{root}}

### GET Distritos
GET {{baseUrl}}/distritos
X-Api-Key: {{api_key}}

### GET 6 Distrito Saltillo
GET {{baseUrl}}/distritos/6
X-Api-Key: {{api_key}}

### GET Oficinas del Distrito 6
GET {{baseUrl}}/oficinas
    ?distrito_id=6
X-Api-Key: {{api_key}}

### Oficina 71 J TERCERO FAMILIAR SALTILLO
GET {{baseUrl}}/oficinas/71
X-Api-Key: {{api_key}}

### GET Servicios de la Oficina
GET {{baseUrl}}/cit_oficinas_servicios
    ?oficina_id=71
X-Api-Key: {{api_key}}

### GET Dias para elegir
GET {{baseUrl}}/cit_dias_disponibles
    ?oficina_id=71
X-Api-Key: {{api_key}}

### GET Horas para elegir
GET {{baseUrl}}/cit_horas_disponibles
    ?oficina_id=71
    &cit_servicio_id=2
    &fecha=2022-09-20
X-Api-Key: {{api_key}}

### GET Cliente por ID
GET {{baseUrl}}/cit_clientes/perfil
    ?cit_cliente_id=99999
X-Api-Key: {{api_key}}

### GET Cliente por email
GET {{baseUrl}}/cit_clientes/perfil
    ?cit_cliente_email=noname@company.com
X-Api-Key: {{api_key}}

### GET Cliente por CURP
GET {{baseUrl}}/cit_clientes/perfil
    ?cit_cliente_curp=XXXX
X-Api-Key: {{api_key}}

### POST crear cita PENDIENTE
POST {{baseUrl}}/cit_citas/nueva
X-Api-Key: {{api_key}}

{
    "cit_cliente_id": 3575,
    "oficina_id": 71,
    "cit_servicio_id": 2,
    "fecha": "2022-08-22",
    "hora_minuto": "11:15"
}

### GET mis citas
GET {{baseUrl}}/cit_citas/mis_citas
    ?cit_cliente_id=3575
X-Api-Key: {{api_key}}

### POST cancelar una cita
POST {{baseUrl}}/cit_citas/cancelar
X-Api-Key: {{api_key}}

{
    "cit_cliente_id": 3575,
    "cit_cita_id": 1299
}
