@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v2
@api_key = {{$dotenv API_KEY}}

### Bienvenida
GET {{root}}

### Materias
GET {{baseUrl}}/materias
X-API-Key: {{api_key}}

### Distritos
GET {{baseUrl}}/distritos
X-API-Key: {{api_key}}

### Autoridades
GET {{baseUrl}}/autoridades
X-API-Key: {{api_key}}

### Domicilios
GET {{baseUrl}}/domicilios
X-API-Key: {{api_key}}

### Oficinas
GET {{baseUrl}}/oficinas
X-API-Key: {{api_key}}
