@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v2
@api_key = {{$dotenv API_KEY}}

### Bienvenida
GET {{root}}

### Clientes
GET {{baseUrl}}/cit_clientes
X-Api-Key: {{api_key}}

### Cantidad de clientes creados en los ultimos dias
GET {{baseUrl}}/cit_clientes/creados_por_dia
    ?size=5
X-Api-Key: {{api_key}}

### Cantidad de clientes creados el 2022-09-01
GET {{baseUrl}}/cit_clientes/creados_por_dia
    ?creado=2022-09-01
X-Api-Key: {{api_key}}

### Cantidad de clientes creados en un rango de fechas
GET {{baseUrl}}/cit_clientes/creados_por_dia
    ?creado_desde=2022-09-01
    &creado_hasta=2022-09-15
X-Api-Key: {{api_key}}
