@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v2
@api_key = {{$dotenv API_KEY}}

### Bienvenida
GET {{root}}

### Citas
GET {{baseUrl}}/cit_citas
X-API-Key: {{api_key}}

### Cantidad de citas creadas en los ultimos 30 dias
GET {{baseUrl}}/cit_citas/creados_por_dia
X-API-Key: {{api_key}}

### Cantidad de citas creadas el 2022-07-23
GET {{baseUrl}}/cit_citas/creados_por_dia
    ?creado=2022-07-23
X-API-Key: {{api_key}}

### Cantidad de citas creadas desde el 2020-07-23 hasta el 2020-07-26
GET {{baseUrl}}/cit_citas/creados_por_dia
    ?creado_desde=2022-07-23
    &creado_hasta=2022-07-26
X-API-Key: {{api_key}}
