@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v2
@api_key = {{$dotenv API_KEY}}

### Bienvenida
GET {{root}}

### Citas PENDIENTE de un juzgado
GET {{baseUrl}}/cit_citas
    ?oficina_clave=SLT-J1-FAM
    &estado=PENDIENTE
    &inicio=2022-09-26
X-Api-Key: {{api_key}}

### Citas PENDIENTE de un cliente
GET {{baseUrl}}/cit_citas
    ?cit_cliente_email=no.existe@company.com
    &inicio_desde=2022-09-15
X-Api-Key: {{api_key}}

### Cantidad de citas creadas, ultimos dias
GET {{baseUrl}}/cit_citas/creados_por_dia
    ?size=4
X-Api-Key: {{api_key}}

### Cantidad de citas creadas en 2022-09-01
GET {{baseUrl}}/cit_citas/creados_por_dia
    ?creado=2022-09-01
X-Api-Key: {{api_key}}

### Cantidad de citas creadas en un rango de fechas
GET {{baseUrl}}/cit_citas/creados_por_dia
    ?creado_desde=2022-09-01
    &creado_hasta=2022-09-15
X-Api-Key: {{api_key}}

### Cantidad de citas agendadas por oficina y por servicio
GET {{baseUrl}}/cit_citas/agendadas_por_servicio_oficina
    ?inicio=2022-09-13
X-Api-Key: {{api_key}}

### Cantidad de citas disponibles
GET {{baseUrl}}/cit_citas/disponibles
    ?cit_cliente_id=4067
X-Api-Key: {{api_key}}

### Cantidad de citas disponibles
GET {{baseUrl}}/cit_citas/disponibles
    ?cit_cliente_curp=XXXX00000000000000
X-Api-Key: {{api_key}}

### Cantidad de citas disponibles
GET {{baseUrl}}/cit_citas/disponibles
    ?cit_cliente_email=no.existe@company.com
X-Api-Key: {{api_key}}
