@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v2
@api_key = {{$dotenv API_KEY}}

### Bienvenida
GET {{root}}

### Recuperaciones
GET {{baseUrl}}/cit_clientes_recuperaciones
X-Api-Key: {{api_key}}

### Cantidad de recuperaciones creados en los ultimos 30 dias
GET {{baseUrl}}/cit_clientes_recuperaciones/creados_por_dia
    ?size=5
X-Api-Key: {{api_key}}

### Cantidad de recuperaciones creados el 2022-07-23
GET {{baseUrl}}/cit_clientes_recuperaciones/creados_por_dia
    ?creado=2022-09-01
X-Api-Key: {{api_key}}

### Cantidad de recuperaciones creados desde el 2020-07-23 hasta el 2020-07-26
GET {{baseUrl}}/cit_clientes_recuperaciones/creados_por_dia
    ?creado_desde=2022-09-01
    &creado_hasta=2022-09-15
X-Api-Key: {{api_key}}
