@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v2
@api_key = {{$dotenv API_KEY}}

### Bienvenida
GET {{root}}

### GET Encuestas de servicios
GET {{baseUrl}}/enc_sistemas
X-Api-Key: {{api_key}}

### GET Detalle
GET {{baseUrl}}/enc_sistemas/2
X-Api-Key: {{api_key}}

### GET Cliente
GET {{baseUrl}}/cit_clientes/3976
X-Api-Key: {{api_key}}

### GET Tiene una encuesta pendiente?
GET {{baseUrl}}/enc_sistemas/pendiente
    ?cit_cliente_id=3976
X-Api-Key: {{api_key}}

### GET Tiene una encuesta pendiente?
GET {{baseUrl}}/enc_sistemas/pendiente
    ?cit_cliente_curp=XXXX00000000000000
X-Api-Key: {{api_key}}

### GET Tiene una encuesta pendiente?
GET {{baseUrl}}/enc_sistemas/pendiente
    ?cit_cliente_email=no.existe@company.com
X-Api-Key: {{api_key}}
