@root = {{$dotenv HOST}}
@baseUrl = {{root}}/v2
@api_key = {{$dotenv API_KEY}}

### Bienvenida
GET {{root}}
X-Api-Key: {{api_key}}

### Modulos
GET {{baseUrl}}/modulos
X-Api-Key: {{api_key}}

### Roles
GET {{baseUrl}}/roles
X-Api-Key: {{api_key}}

### Rol 1 ADMINISTRADOR
GET {{baseUrl}}/roles/1
X-Api-Key: {{api_key}}

### Permisos del rol 1 ADMINISTRADOR
GET {{baseUrl}}/roles/1/permisos
X-Api-Key: {{api_key}}

### Usuarios del rol 1 ADMINISTRADOR
GET {{baseUrl}}/roles/1/usuarios
X-Api-Key: {{api_key}}

### Rol 3 JUZGADO PRIMERA INSTANCIA
GET {{baseUrl}}/roles/3
X-Api-Key: {{api_key}}

### Permisos del rol 3 JUZGADO PRIMERA INSTANCIA
GET {{baseUrl}}/roles/3/permisos
X-Api-Key: {{api_key}}

### Usuarios del rol 3 JUZGADO PRIMERA INSTANCIA
GET {{baseUrl}}/roles/3/usuarios
X-Api-Key: {{api_key}}

### Permisos
GET {{baseUrl}}/permisos
X-Api-Key: {{api_key}}

### Usuarios
GET {{baseUrl}}/usuarios
X-Api-Key: {{api_key}}

### Usuarios eliminados
GET {{baseUrl}}/usuarios
    ?estatus=B
X-Api-Key: {{api_key}}

### Usuarios-Roles
GET {{baseUrl}}/usuarios_roles
X-Api-Key: {{api_key}}
